### ISSUE TITLE
Send fallback text instead of nothing if STT fails

### ISSUE THREAD

**Issue by tannisroot** [rhasspy/wyoming-rhasspy-speech#5]
If you say an unsupported command, rhasspy-speech will send `stt-no-text-recognized" and the pipeline will fail, providing the user with no feedback. 
This is not user friendly as I expect my Satellite to say something like "Sorry, I couldn't understand that" if no speech was recognized.
Instead, now, after saying an invalid request, all I get is silence, which makes me think it's just processing the request way too long. 
Ideally this is something that should be handled in HA with any STT provider, but currently only rhasspy-speech runs into this problem afaik.

**Comment by flubshi** [comment]
From documentation I assume that you can define `unknown_sentence_response` in sentences yaml:

```yaml
sentences:
  [...]
lists:
  [...]
unknown_sentence_response: "Sorry, I couldn't understand that"
```
